### ISSUE TITLE
Implement RFC4880 3.7.1.3 Iterated and Salted S2K

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#114]
As title. Location: https://github.com/riboseinc/rnp/blob/f20e993e7b7e9e11e70f9b71f1db2b005746454c/src/lib/create.c#L481

**Comment by randombit** [comment]
Maybe useful reference, Botan used to include this (was dropped some years ago because it was not particularly useful outside the context of a full PGP impl, and hey here we are). The last commit before it was removed is

https://github.com/randombit/botan/tree/75db296a459a9e25b112207707cc5e26a6f2b872/src/pbkdf/pgps2k

**Comment by ronaldtse** [comment]
Things do come circle! @randombit any chance of re-instating this in botan?

**Comment by randombit** [comment]
@ronaldtse Yes I think re-adding this to Botan (as well as the non-iterated S2K currently implemented in rnp) then changing rnp to use the PBKDF ffi interface is the way to go.

**Comment by randombit** [comment]
Weirdly packet-parse.c already implements iterated S2K, but create.c doesn't, and it appears there is a third implementation of it in `ssh2pgp.c`. Yuk. Anyway I'll clean all that up as part of this issue.

**Comment by ronaldtse** [comment]
You must have had a good idea in mind when you found all these 3 implementations. Thanks @randombit 😄

**Comment by ronaldtse** [comment]
Closed with #140 .
