### ISSUE TITLE
Come up with consistent return values

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#153]
The code base seems to have a mixture of functions returning different values indicating success, failure, other conditions.
I think we should come up with a standard and stick to it.
I think we may benefit from some macros like `RNP_OK(call_some_func())`/`RNP_OK(retval)` as well.
I'd like to dig into this some more. Botan has a convention for the FFI interface that might be a good fit.

**Comment by ronaldtse** [comment]
Nice one @dewyatt ! The macro approach does look good.

**Comment by dewyatt** [comment]
@flowher Indeed, it's partially a dupe.
I think you mean `pgp_errcode_t`, which does provide a decent set of errors that are used in a lot of the modules.
However, a common convention is for errors to be <0 when using int return values.
Some functions return buffer sizes or have other positive return values that indicate different successful conditions, for example, so a positive error value can't be used with those.
So we may want to rework that a bit.

Those error codes are currently mostly used with the pgp_error_t linked list, so you can read multiple parse errors, etc.
I think this issue is more about the ultimate return values of functions, but it would probably make sense to utilize pgp_errcode_t (though I think negative error codes would make more sense here).

**Comment by flowher** [comment]
hmm... I'm not sure why returning `<0` as an error code is better than returning `>0`. Buffer size is actually `size_t`, it's wise not to cast it to `int`, so I think it is good example why not to do it.
We can always return values by pointer, so that's not a problem. If we assume that all our functions alwyas return error code and results are always returned by pointer, then it makes quite unified API. Also caller is less likely to make a mistake - when returning int, caller must first check if returned value is <>0 and take different action depending on returned value.

**Comment by dewyatt** [comment]
@flowher It's a very common convention, see the Linux kernel, botan FFI API, etc.
On size_t, you're right, and some of the existing functions do handle this incorrectly.

**Comment by flowher** [comment]
I know posix style is common practice (but not necessarily good). Whatever type we return (signed or unsigned), we should be should be using `pgp_errcode_t` (you can always return `-pgp_errcode_t`).

**Comment by dewyatt** [comment]
Agreed that we don't want to duplicate error codes.

**Comment by ni4** [comment]
I partially made this easier in PR #258 by introducing RNP_OK/RNP_FAIL instead of 1 and 0, so later on it would be easier to search-and-replace if we get to other solution. The problem of pgp_errcode_t is that it is _OK for 0, while most of functions use 1 for success, and their callers use this fact in boolean expressions. Changing this behavior is potential source of hard to find errors.

**Comment by flowher** [comment]
A bit of context here.

### What's the problem with inconsistent values
Our functions sometimes return -1 sometimes 0 and sometimes 1 in order to indicate error. Problem is amplified by the fact that documentation of the functions (API interfaces included) is nonexistent. 

Developers should "code to interface not implementation". What developer will do in order to use the function? Currently he is forced to check code of the function and implement calling code according to implementation (not interface). 
This is "not good" because it means that whenever callee is changed (for example it returns 1 in case of error instead of -1) we need to look at all the callers and align with new behaviour.  In some cases it is not possible (external applications calling ``rnp`` functions from ``rnp.h``)

It is worth to notice that root of the whole problem starts at point when someone had an idea to use ``int`` as a type to describe error code. 

### 0 means true
In some places of the code we introduced (git ``3928664e``) defines ``RNP_OK==1``  and ``RNP_FAILED==0``. Those macros were introduced in order to easy "grepping" for places where code must be changed (debatable if it is useful or not, but that was a goal). Now - this approach obviously makes whole situation even worse than it was. Why? Because, there will be one value for success and multiple values for some kind of failure. As soon as someone introduces another error code it will have value different then 0. So my calling code for a function that returns ``RNP_*`` may look like that (please notice, function returns ``int``).

```
if (do_stuff()) {
   ... all good ..
} else {
   ... handle error ...
}
```

Now, imagine ``do_stuff`` evolves and returns new error code - is calling code is broken? Yes. So, let 0 be new true!  Let ``RNP_`` stuff die.

### Argument "But changing current implementation is so complicated"
It will be painful and complicated and error prone and that's a price. It will be more painful if someone starts using API in current state. Then changing it will be really painful.

 In order to make it less  painful - each newly added function, if it returns error code it should use ``pgp_error_t`` (or introduce something better if you wish). 
Also changing API in ``rnp.h`` is low hanging fruit - it's easy to change and brings a lot of value.

### How to fix
* Don't use ``int`` that's a type which describes integer, not type for error codes.
* Functions should either return true/false (if appropriate)  - when bool is compared with int then user gets a warning (-Wall). If we treat all warnings as errors, such code will never compile, so we eliminate stupid bugs
```
tmp.c:14:12: warning: comparison of constant ‘10’ with boolean expression is always false [-Wbool-compare]
     if (10 == x) {
```

* For cases where bool can't be used - let's define type that only describes error codes and return those guys (either it is ``pgp_error_t`` or something else, but type specific to errors).
* Another approach - return value should alwyas be either possitive or negative. This forces  caller (by convention) to always compare result against expected value (code ``if(do_stuff())`` is wrong as it always take same branch)

**Comment by dewyatt** [comment]
> It is worth to notice that root of the whole problem starts at point when someone had an idea to use int as a type to describe error code.

Personally I think the root of the problem was not having a set convention.

> 0 means true
> So, let 0 be new true!

Agreed, this is an overwhelmingly common convention in my experience. 

> Argument "But changing current implementation is so complicated"

I think we can all agree that this has never been a valid argument. The change has to happen, though it may be painful.

> Functions should either return true/false (if appropriate)

I would say this is OK so long as the function has no failure points (no malloc, etc). The caller should always be able to determine 1) if a function failed and 2) why it failed. If a failure point is later added, the return type should be changed.

> In order to make it less painful - each newly added function, if it returns error code it should use pgp_error_t
> Don't use int that's a type which describes integer, not type for error codes.

AFAIK one of these has a size that does not change on the same platform, the other does not. Returning pgp_error_t sounds nice on the surface, but could also introduce ABI issues.

Anyways, I'm going to leave this to you to debate.

**Comment by flowher** [comment]
Ok

**Comment by ni4** [comment]
Agree with @dewyatt on the fact that the root of the problem is the lack of convention. Personally I don't care whether 0 or true or 5 or whatever else will mean the success. We just need to set the convention, and stick to it.

However it would be much better to change all library code to stick to this new convention at once, in a single PR, instead of adding new functions with new convention and leaving old code as it is.

**Comment by flowher** [comment]
Convention is good, forcing convention would be better. I think it's already clear that it doesn't matter what value we use for success (as I wrote there are two approaches) as long as it's sane. 
I think it should be done gradually, so that change is carefully reviewed. It is not likely it will be done in one commit.

**Comment by flowher** [comment]
So then, let's say we do it easy way - we define return type as

``typedef uint32_t rnp_error_t`` 

Then:
1. I think this type will be ABI compatible across all compilers and systems (to be double checked). But this is already better than ``int``,  ``enum`` and it also defines convention
2. We have 32 bits to use - it mean we can define an error with a lot of details if we use it as a bitmask. So for example bits 1,2,3 would keep information about origin of an error (file system/malloc/crypto/... whatever), bits 4,5,6 could keep information about algorithm used (DH,RSA,...) etc. 

That's a bit what someone tried to do with ``pgp_error_t`` but using enum here seem to be poor idea.

**Comment by dewyatt** [comment]
> returning int and returning typedef int ReturnType_t are two different things

They're technically synonymous (standard says `A typedef declaration does not introduce a new type, only a
synonym for the type so specified`), but perhaps you mean conceptually? Like they communicate different things to the reader? I do agree on that.

> why pgp_error_t was implemented in a first place?

The `pgp_errcode_t` enum was part of the original OpenPGP-SDK, where it was used only in a linked-list for the multiple errors that could occur during certain operations, it was never returned directly from functions. `pgp_parse`, for example, can encounter numerous errors but continue on, and the user can access all the errors encountered via `stream->errors`.

(Just a side note but we all keep writing `pgp_error_t` when we probably mean `pgp_errcode_t`. One is a struct, one is a typedef'd enum.)

> typedef uint32_t rnp_error_t

I don't have any immediate concerns with this.

> use it as a bitmask

I think this would be overcomplicating things, personally. I can imaging frustrated users of the API doing direct comparisons on the error codes and wondering why things don't make sense. Sure, we can say RTFM, but that's not likely to endear users of the API.

**Comment by flowher** [comment]
|  but perhaps you mean conceptually? Like they communicate different things to the reader? 
Yes, ``typedef`` doesn't define  a real type (unfortunately), that's why I prefer to use bool (which is real type and compilers know about it). In the end it's just C, but still typedef gives clear indication of "what is this thing that function returns".

| I think this would be overcomplicating things.

This is true and I'm not sure if we really need something complicated - maybe simple list of errors is OK. Nevertheless, in this solution there is only one list of errors - errors may have different flags (which are not error codes), but there is one single list of errors. So problem with comparing as you described above, doesn't really exist. But still, ``rnp`` is not that complicated as other libraries (I've seen this solution in openssl I think). so... not sure it's what we need. And if we will need, we can always change it as change would code compatible.

**Comment by ronaldtse** [comment]
I think most of us agree on most of these answers:
* We stick to `typedef uint32_t rnp_error_t` across the board, and enforce convention. Maybe a large PR?
* Add doxygen documentation to every function whenever a developer edits it.

Then the next step is, can we have a set of error codes / messages?

**Comment by dewyatt** [comment]
Thinking back on this:

>   Functions should either return true/false (if appropriate)
> I would say this is OK so long as the function has no failure points (no malloc, etc). The caller should always be able to determine 1) if a function failed and 2) why it failed. If a failure point is later added, the return type should be changed.

It's probably not a good idea to return bool, given the tendency for functions to evolve as mentioned. Changing the return type from bool to a uint32_t/rnp_error_t/whatever is an ABI breaking change, so it's probably safer to always return an error code and avoid bool.

**Comment by flowher** [comment]
Well, it depends what function does.

**Comment by ronaldtse** [comment]
Agree with @flowher . We should first define the user-facing API (and FFI), right? Maybe we can get that going?

**Comment by ni4** [comment]
Agree on uin32_t for errors. And regarding the API - we should define user-faced API for the library, and then get stick to those function signatures without breaking changes.

**Comment by flowher** [comment]
One good rule of thumb is - don't add API functions until they are absolutely needed (then you don't have to stick to it).

**Comment by flowher** [comment]
IMHO regarding API, we should only define functions which are *absolutely needed*, have clear definition for current implementation (not future one) and there is no question regarding how to use it. And then stick to such interface.

**Comment by dewyatt** [comment]
> flowher: Definitely it's not good to generalize by saying that it is always bad to return bool .

Perhaps, but don't you think it can be a bit error-prone?

In "Practical C", for example, the author warns: `Personally, I'm not so fond of these definitions [stdbool.h] because they provide a false sense of security: they make you think that a variable of type bool can only have two values.` and goes on to demonstrate this.

Linus has a similar list of reasons he is [not a fan of bool](https://lkml.org/lkml/2013/8/31/138).

And as an example, things like this are perfectly valid and won't typically cause any warnings:

```c
bool is_thing_set() {
    return 55;
}
bool is_thing_set2() {
    return "I don't know, is it?";
}
```

Something more realistic and harder to spot would probably involve a bool function returning a call to another function that returns a non-bool.

Some static analysis tools do spot these things, but likely only the simplest cases.

> flowher: Sometimes you don't care about ABI.

That view may be OK in the early stages, but I think once we start packaging something stable, we should be much more careful. ABI breaking changes can mean new major package releases, maintaining a new code branch, potentially back-porting security fixes, etc, etc.

I think mixing `uint32_t` and `bool` may end up being potentially error-prone and I felt more comfortable with your previous view (`flowher: If we assume that all our functions alwyas return error code and results are always returned by pointer, then it makes quite unified API.`).

Anyways, I think that's about all I have to say on the subject of return values and it seems I've been overruled anyhow.

@flowher Can you do a PR to update the dev guide with specific guidelines on this, so we can close this issue and start enforcing a convention?

**Comment by dewyatt** [comment]
> We should first define the user-facing API (and FFI), right? Maybe we can get that going?

@ronaldtse IMO rnp isn't very stable internally and that makes this a bit more difficult to do just yet. We still have very minimal test coverage, large changes occurring, lots of open bugs, etc. I think there's still a bit of chaos.

**Comment by flowher** [comment]
@dewyatt I think you are thinking about return codes from public API and this PR is about return codes from any function. Ok I'll do PR

**Comment by flowher** [comment]
This is what I'm using

```
/* -----------------------------------------------------------------------------
 * @brief   brief      
 *          
 * @param   param   
 *          
 * @remarks (optional) remarks 
 * 
 * @pre (optional) assumptions about parameters (like must be not null)
 *
 * @returns (if returns)
 *
-------------------------------------------------------------------------------- */
```

**Comment by ronaldtse** [comment]
@dewyatt I meant that we need to define the *desired* user-facing API so we know how to get there. We need a solid goal for us to really streamline development to settle the chaos 👍

**Comment by dewyatt** [comment]
@flowher Will you be able to do the PR for the function return values soon? @ronaldtse has some deadlines and I think this would help in stabilizing things.

**Comment by flowher** [comment]
yes, I've started this in my ECDH dev. But I'll do separated PR for this + improved RNP_LOG() + I want to move all crypto code into separated directory and have "crypto.h" the single header for crypto. This is going to be done this week

**Comment by flowher** [comment]
I think this can be closed now.
