### ISSUE TITLE
rnp key generation doesn't seem to consume entropy like GnuPG

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#202]
From @frank-trampe : 

> Does rnp use less entropy than gpg? Key generation is almost instantaneous, like generating keys with the transient option in gpg.

GnuPG key generation usually takes ages on a headless machine unless additional entropy is fed, such as when `rngd` is enabled.

**Comment by ni4** [comment]
RSA key generation time cannot be guessed in any way since completely depends on how lucky you are on choosing the random initial number and then searching for the prime based on that number. For DSA/EC-based algorithms it would be the same since requires just one random number generation and then some calculations.

**Comment by randombit** [comment]
Botan doesn't block for entropy - it uses either `/dev/urandom` or else a userspace PRNG seeded with output from `/dev/random` (and/or other sources). In rnp's case it always passes NULL as the `rng_type` param to `botan_rng_init`, so botan will use `/dev/urandom` if it is available (or otherwise falls back to the userspace PRNG).

**Comment by ronaldtse** [comment]
Since this isn't a problem for us I'm closing this, thanks @ni4 @randombit @frank-trampe !
