### ISSUE TITLE
C standard (C99/C11)

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#321]
## Description

I propose to update developer guide to reflect following assumptions

* code of the library should be compatible with C11
* public API of the library should be compatible with C99 (so we basically don't expose anything that's C11 specific in public headers)

Currently we are compiling with C11. Maybe what we want is to be compatible on API level with older compilers/standards (if not then I prefer C11 for everything). I don't being compatible with something older than C99 makes much sense.

Other options is to use C99 for everything, which is also OK, but maybe a shame not to use features of C11.

Any objections?

**Comment by dewyatt** [comment]
:thumbsup: on C99-compatible public headers.
:thumbsup: on not worrying much about C89/C90-compatibility.

So for me the question is whether we want to use C11 internally. Honestly, the only reason we currently build with C11 is because someone started using some C11 features at some point and it broke clang compilation (which tends to be a bit stricter). So I added it as a temporary fix: https://github.com/riboseinc/rnp/pull/117#issuecomment-304038207

> a shame not to use features of C11.

IMO C11 doesn't provide a whole lot. So I'm not sure it would add much and it would reduce portability some. Plus you have to careful about which C11 features you use. Even now in 2017, for example, glibc does not implement the (optional) C11 thread support. I would guess that support is pretty spotty on some platforms.

**Comment by flowher** [comment]
I'm good with not using C11. True, it doesn't provide a lot of features. Just would be good to fix it to certain version, so that it's clear we should/shouldn't use C11 features.

**Comment by ronaldtse** [comment]
It sounds like we should focus on C99, and rewrite the parts that need C11. Anyone interested in doing so?

**Comment by flowher** [comment]
I can take it on my stack. Except if anybody else interested

**Comment by ni4** [comment]
Just understand that C99 doesn't support anonymous unions/structs, while C11 does.
It's a minor thing but I like it since you can write `compression_params->z` or `compression_params->bz` instead of `compression_params->zparams->z`

So, will we move back to C99 or it is okay to use C11 features?

**Comment by dewyatt** [comment]
> Just understand that C99 doesn't support anonymous unions/structs, while C11 does.

True but anonymous structs are incompatible with (ISO) C++ for example, so they can cause problems in public headers.

The problems I see with C11 are:
* It doesn't really provide much, as discussed above.
* It reduces portability since it's pretty new (as far as language standards). For example, I believe MSVC only added partial C99 support in 2013 (~14 years after the standard was published).
* It has too many optional pieces and it's hard to spot them in code reviews, so they creep into the code base and we only discover portability issues later on. (This has already happened)

So my opinion is that we're better off sticking to C99 as much as possible. The main C11 feature we're currently using is typdef redeclarations, which is mostly a temporary measure to aid in decoupling things.

**Comment by flowher** [comment]
> So my opinion is that we're better off sticking to C99 as much as possible. The main C11 feature we're currently using is typdef redeclarations, which is mostly a temporary measure to aid in decoupling things.

I don't think we have many typdef redeclarations (I see only one at the moment). So even that shouldn't be a problem.

**Comment by ronaldtse** [comment]
Then @flowher could you help us update all code to be compliant with C99? Thanks!

**Comment by flowher** [comment]
Ok

**Comment by ni4** [comment]
@ronaldtse While we are already on C++ instead of C99, so this can be closed?

**Comment by ronaldtse** [comment]
Agree, thanks @ni4 !
