### ISSUE TITLE
Build on macOS fails because memset_s is not available

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#387]
## Description

After recent changes code doesn't build on macOS with error message `error: implicit declaration of function 'memset_s' is invalid in C99`

Adding the following code fixes the issue, however is this a correct solution?
```c
#if defined(HAVE_MEMSET_S)
    #define __STDC_WANT_LIB_EXT1__ 1
#endif
#include <string.h>
```

**Comment by ni4** [comment]
@dewyatt, @ronaldtse what do you think?

**Comment by dewyatt** [comment]
Oops I remember seeing this in ruby's handling of this functionality ([here](https://github.com/ruby/ruby/commit/09bdb7913c0bf7f2b15d1c7f46b566e35fc5eb82)) and forgot to add that in.
Eventually I guess I'll have to get macOS added in to Travis. I've just been avoiding it since I know it requires full VMs and will probably slow CI down 10x compared to the current containers.

> Adding the following code fixes the issue, however is this a correct solution?

I'll actually need to do some more work on this, because I'm using AC_CHECK_FUNCS when we have different compiler flags set.

**Comment by randombit** [comment]
Alternative would be to use the botan FFI function `botan_scrub_mem` and avoid the hassle of the `explicit_bzero` support.

**Comment by dewyatt** [comment]
> Alternative would be to use the botan FFI function botan_scrub_mem and avoid the hassle of the explicit_bzero support.

@randombit I completely forgot about that! I remember seeing it a few weeks ago. That should be much simpler.

**Comment by dewyatt** [comment]
Should be all good after https://github.com/riboseinc/rnp/pull/391. Please re-open if not.
