### ISSUE TITLE
Rarely reproducible problem with RSA keys during decryption/verification

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#400]
## Description

Rarely after number of runs of `./cli_tests.py` encryption/decryption or signing/verification tests fails, and only in one case (i.e. with the same rnp-generated key one round of encryption/decryption or signing/verification fails and then works fine).
I suspect some 'edge case' like symmetric key wrapping/unwrapping/bit boundary or so on problem.

This should be reproduced and further investigated.

**Comment by ni4** [comment]
This can be reproduced with the following python CLI test sample:

```python
def rnp_sign_bug_hunt():
    for i in range(0, 100):
        rnp_genkey_rsa(KEY_SIGN_GPG)
        gpg_import_pubring()
        gpg_import_secring()
        
        for j in range(0, 30):
            run_test(rnp_signing_gpg_to_rnp, 15000, 0, 1)
        clear_keyrings()
```

It happens after number of runs with the same key, so it could be related to some wrong key calculations. Signature is generated by GPG, and verification fails in both GPG and RNP. So it could be even bug in the GPG.

**Comment by dewyatt** [comment]
This does seem like a gpg bug (or two).
I created a couple of repos with reduced cases if it helps (and unencrypted keys, as the key material may be relevant here):
https://github.com/dewyatt/gpg-bug-decrypting
https://github.com/dewyatt/gpg-bug-signing

They both succeed most of the time, but will usually fail within a minute or so. The decryption bug repo is particularly interesting because it uses static data (which it randomly fails to decrypt).
Using gpg1 instead makes both issues disappear so it seems like a regression (maybe related to gpg-agent? or libgcrypt?).

I wasn't able to reproduce the issue with keys that were not generated by rnp. Anyways, good luck on this @ni4!

**Comment by ni4** [comment]
Thanks @dewyatt for your investigations.
Today I also spent some time on this and found out the reason.
RFC 4880 tells that p < q for RSA key, but we ignored this fact. And looks like GPG relies on this during signing/decryption (there is faster calculation algorithm based on p, q and u).
I'm preparing PR right now.
