### ISSUE TITLE
Question about key generation

### ISSUE THREAD

**Issue by catap** [riboseinc/rnp#410]
@dewyatt, how I see you're last one who touch this code, so, I think the question is to you but I may be wrong.

Let get the sample of code:
```c
bool
pgp_generate_primary_key(rnp_keygen_primary_desc_t *desc,
                         bool                       merge_defaults,
                         pgp_key_t *                primary_sec,
                         pgp_key_t *                primary_pub,
                         pgp_seckey_t *             decrypted_seckey)
{
    ....
    // generate the raw key pair
    if (!pgp_generate_seckey(&desc->crypto, &seckey)) {
        goto end;
    }

    // write the secret key, userid, and self-signature
    if (!pgp_setup_memory_write(NULL, &output, &mem, 4096)) {
        goto end;
    }
    if (!pgp_write_struct_seckey(
          PGP_PTAG_CT_SECRET_KEY, &seckey, desc->crypto.passphrase, output) ||
        !pgp_write_struct_userid(output, desc->cert.userid) ||
        !pgp_write_selfsig_cert(output, &seckey, desc->crypto.hash_alg, &desc->cert)) {
        RNP_LOG("failed to write out generated key+sigs");
        goto end;
    }
    // load the secret key back in
    if (!load_generated_key(&output, &mem, primary_sec)) {
        goto end;
    }
    ...
    return ok;
}
```

Here the code generate a new key, write it as PGP key to memory, and after load it from memory. I feel that it might be a security reason to keep as less as possible time when we keep unsecured a secret numbers. Am I right?

If yes, it broke G10 storage because it requests unencrypted numbers to storing.

So, I see two possible way to fix this issue:
 1. Keep a generated key as unsecured in memory before it'd saved by key-store.
 2. G10 should know that key might be encrypted by PGP, and it should decrypt it before saving.

I vote for first option, because a last one requests one more password inputs for encrypting. 

Have you got anything in mind about this?

cc: @ronaldtse

**Comment by dewyatt** [comment]
Right, I mentioned that G10 would be broken in the subkey rework PR and also that I disabled the tests in that PR. The plan was to take another look at re-enabling G10 support sometime soon.

Loading the generated key back in serves a few purposes:

* As you said, it's *slightly* more secure (for the cases when `decrypted_seckey` is not requested by the caller).
* It gives us a consistent view in the `pgp_key_t` structure. For example, previously multiple parts of the structure would be different depending on whether the key was freshly generated or it had been loaded from disk/mem. Also, primary key generation involves adding a userid. For an openpgp key this means that otherwise we would have to 1) add it to the userids dynarray 2) add a self-sig to the packets dynarray 3) add (/parse) it to the subsig dynarray 4) re-evaluate uid0 5) probably adjust key_flags and 6) probably other things I'm forgetting. So re-loading the key was a simpler and quicker solution, given that we had a deadline.

I honestly haven't had time to thoroughly evaluate everything going on with KBX and G10, my focus has always been on the openpgp format because it is the only one that has ever been fully supported. Even if G10 sort of works now, we have the remaining issue that G10 still doesn't store any metadata, and the library likely makes a lot of assumptions that don't hold true for such a format.

As far as possible fixes, I think there's probably other options available apart from the two listed. The way G10 encrypted key loading/saving seems to be currently handled, involves adding [fields](https://github.com/riboseinc/rnp/blob/b9c993a46d4d1da12d5a24ac6bbb11620107f029/src/lib/packet.h#L611) to `pgp_seckey_t`, which I'm not sure is ideal (to me, `pgp_seckey_t` is more of a librepgp thing, but this adds G10 key store-specific fields).

We should probably think on this a bit.

**Comment by catap** [comment]
@dewyatt thanks for explanation.

**Comment by flowher** [comment]
Indeed, would be better if ``pgp_seckey_t`` doesn't contains keystore specific stuff

**Comment by dewyatt** [comment]
I think we're OK on this issue now (G10 now generally works again).

> Indeed, would be better if pgp_seckey_t doesn't contains keystore specific stuff

This is now taken care of as well.
