### ISSUE TITLE
Optimize CFB mode usage

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#440]
## Description

Current CFB mode implementation processes input data by byte, which is quite slow.
It should be optimized to work at least on per-word level.
Other optimization would be to process the whole chunk on botan level so botan_encrypt_block call overhead is not applied for each 8-16 bytes.

**Comment by ni4** [comment]
@ronaldtse @randombit 
As we discussed in some other topic, botan is general purpose cryptography library so it should not implement OpenPGP-specific encryption mode. From the other side, it implements OpenPGP-specific S2K.

Also probably overhead which is added by botan_encrypt_block is not a big deal.

**Comment by ronaldtse** [comment]
Agree with @ni4 that we should not make Botan implement OpenPGP-specific stuff.

Maybe @randombit would have some thoughts on this.

**Comment by randombit** [comment]
Definitely those loops are written as "simplest thing that could possibly work".

Something like the following may help, it amortizes the pointer increments/length decrements over an entire block instead of byte by byte. And instead of returning to the top of the outer `while(bytes)`loop after each byte is processed, it does so only after either consuming all remaining bytes in the message (in which case the loop exits) or all bytes in the CFB buffer (in which case we must handle the `if(crypt->remaining == 0)` case).

```
diff --git a/src/lib/symmetric.c b/src/lib/symmetric.c
index 35f825b..cc84261 100644
--- a/src/lib/symmetric.c
+++ b/src/lib/symmetric.c
@@ -198,14 +198,17 @@ pgp_cipher_cfb_encrypt(pgp_crypt_t *crypt, uint8_t *out, const uint8_t *in, size
             crypt->remaining = crypt->blocksize;
         }
 
-        if (crypt->remaining > 0) {
-            *out = *in ^ crypt->iv[crypt->blocksize - crypt->remaining];
-            crypt->iv[crypt->blocksize - crypt->remaining] = *out;
-            crypt->remaining -= 1;
-            out++;
-            in++;
-            bytes--;
-        }
+        size_t to_process = MIN(bytes, crypt->remaining);
+
+        uint8_t* iv = crypt->iv + (crypt->blocksize - crypt->remaining);
+        for(size_t i = 0; i != to_process; ++i)
+           out[i] = in[i] ^ iv[i];
+        memcpy(iv, out, to_process);
+
+        in += to_process;
+        out += to_process;
+        bytes -= to_process;
+        crypt->remaining -= to_process;
     }
 
     return 0;
```

(Note I have checked this still passes the tests but have not verified that it's any faster.)

Not totally averse to adding PGP-CFB mode to Botan but don't know that it would help performance much. In fact how the cipher interface works for C89 right now, all inputs are copied to a buffer, operated on there, and then copied back out. So it might be even less efficient than the above loop.

Also I think I'd need a better handle on how resyncing actually works, in particular I don't understand why in one resync case we don't encrypt the IV and in another resync case we do (this is pgp_cipher_cfb_resync_v2 vs pgp_cipher_cfb_resync). I added the v2 function in a4b2fb9fee4 but the code previously called `encrypt` directly. However looking at my patch there now, the code I changed was:

```
         if (tag == PGP_PTAG_CT_SE_DATA_BODY) {
-            pgp_cipher_cfb_resync(decrypt);
-            pgp_cipher_block_encrypt(decrypt, decrypt->civ, decrypt->civ);
+            pgp_cipher_cfb_resync_v2(decrypt);
         }
```

But then we found later, in 0fa111d8 that `civ` was not being read at all. So in fact before my patch, this code did a resync, and then kind of randomly encrypted a buffer that was never used, basically a no-op. So probably the `resync_v2` function can be removed and the current caller changed to use `resync`.

The per-call overhead of calling `botan_block_cipher_encrypt_blocks` should be very small, basically just checking a magic `uint32_t` in the header and setting up a `try`/`catch` block. The cost of actually doing the encryption operation is probably 95% of the time there, and that's a constant regardless of where the CFB mode is implemented.

**Comment by ni4** [comment]
@randombit The cycle can be optimized for larger blocks even further by moving from byte-to-byte xoring to the whole block xoring, i.e.:
- process bytes till the block boundary;
- process all full blocks using uint32_t/uint64_t (depending on architecture) xors with constant increments 
- process the tail using byte xors/cycle

If nobody wants to deal with this I can take the issue later on, anyway I'm working on symmetric encryption/decryption right now.

P.S. Regarding resync - it is a bit different for old packets/new packets as far as I remember. Anyway I can work on this as well.
