### ISSUE TITLE
Make indentation whitespace consistent throughout code

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#61]
Right now the code uses a mix of tabs and spaces for indentation. We should make it consistent and document the choice in a "Contribution guidelines" section of README.

**Comment by dewyatt** [comment]
Some conventions we should probably nail down:

- Indentation (tabs vs spaces, count, etc.)
- General style (K&R etc.)
- General return values (int vs unsigned). Some functions return 0/1, some return -1, etc.

We may want to pull some of the C-specific portions of [Google's C/C++ style guide](https://google.github.io/styleguide/cppguide.html).

**Comment by ronaldtse** [comment]
@dewyatt thanks for this. Would you mind being the coordinator for this and authoritatively set the rules in a "Contribution Guidelines" section within `README.md`?

**Comment by dewyatt** [comment]
Closed in 48d36df5a9ae2aa51a00c72f0ebce16b4aa26f59

**Comment by dewyatt** [comment]
I think I better re-open this because:

1. I missed `include/rnp.h` in the re-format (oops).  I think I must have been in the `src/` subdir instead of top-level like I should have been.
2. Clang 5.0.0 apparently fixes block comment alignment, so I'd like to evaluate whether it's feasible to get everyone on that version.
3. There are still some stubborn tabs in the source that I should purge.
