### ISSUE TITLE
Clang build with sanitizers is broken

### ISSUE THREAD

**Issue by henrydcase** [riboseinc/rnp#610]
## Description

Seems our build with clang sanitizers was always red so nobody looks at it, but now it seems it doesn't even run:

https://travis-ci.org/riboseinc/rnp/jobs/334984424 (build for commit d3cb665 - current head)

Not sure when it was broken

**Comment by ni4** [comment]
This should be because of leak sanitizer, I got (the same?) problem on macOS:
`clang: error: unsupported option '-fsanitize=leak' for target 'x86_64-apple-darwin16.7.0`

**Comment by dewyatt** [comment]
This is only the sanitize-leaks build, which we have always explicitly allowed to fail (until we have fixed every leak in our test runs).

It looks like LSan requires ptrace, which isn't currently permitted in travis containers: https://github.com/travis-ci/travis-ci/issues/9033

We could use a VM for that particular build, but since we don't really use this build I think it probably makes more sense to just wait and see how travis responds. You can always run it locally with something like:

`docker run --cap-add SYS_PTRACE -ti --rm travisci/ci-garnet:packer-1512502276-986baf0 bash -l`.

@ni4 Your issue appears to be different. LSan should work on macOS [AFAIK](https://clang.llvm.org/docs/LeakSanitizer.html).

**Comment by dewyatt** [comment]
Fixed in the PR referenced, closing.
