### ISSUE TITLE
Create FFI interface for external bindings

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#64]
@dewyatt commented that our code changes has been breaking ruby-rnp and we should adopt a stable FFI interface for external bindings.

**Comment by ronaldtse** [comment]
Thanks @dewyatt for handling this!

**Comment by dewyatt** [comment]
It looks like ruby-rnp is broken for a few reasons:
1. The switch to using Botan as a BIGNUM provider caused some things to break since it's all a bit too tightly coupled. I'm sure I can abstract this away with a dedicated FFI interface in rnp to make things more resilient.
2. All signatures generated by rnp are invalid at the moment. I'm guessing this is known and is just part of the work Jack is doing right now.

I think the best course of action is probably going to be moving anything I can from ruby-rnp into rnp itself, and then providing a very minimal FFI interface to that. I think better subkey handling is probably one of the things we need in rnp itself, before I can provide this FFI interface.

**Comment by randombit** [comment]
@dewyatt Re "All signatures generated by rnp are invalid at the moment." not expected! My PKCS change should not have changed signature handling at all, but I'll admit I only tested my patch with encrypt/decrypt. :( I will investigate this but won't have time until the weekend at earliest or more likely middle of next week.

**Comment by dewyatt** [comment]
@randombit Oh! I'll go ahead and file a separate issue with more info then.

**Comment by ronaldtse** [comment]
Thanks @dewyatt , perhaps could you also specify in a separate issue how we can better handle subkeys? I suppose that meant better subkey generation, signing of them and usage?

**Comment by dewyatt** [comment]
@ronaldtse I'll have to check again but I think what I was thinking about was mostly what I wrote in  https://github.com/riboseinc/rnp/issues/35 (which I forgot about).

Basically I work around some of these limitations in ruby-rnp, but that does make it a bit more fragile. So everything that's lacking in rnp, I need to get taken care of, and then add this FFI interface and utilize it in ruby-rnp.

**Comment by ronaldtse** [comment]
Agree @dewyatt !

**Comment by ronaldtse** [comment]
It seems to be time we take care of the FFI -- @dewyatt do you need any help with this? I'm sure everyone has an opinion on the interface 😄

**Comment by dewyatt** [comment]
If someone else wants to tackle this, please do. I believe botan's FFI interface is a good model, as well as the API Jack mentions in https://github.com/riboseinc/rnp/issues/167.

We will also need to rework subkey handling to provide a full FFI interface.

**Comment by ronaldtse** [comment]
@dewyatt can we close this? Thanks!

**Comment by dewyatt** [comment]
Yes!
