### ISSUE TITLE
FFI API discussion - process / protect

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#648]
## Description

@ni4 posted a message that I missed, just going to quote it here for discussion:

> Now, when encrypt-and-sign is implemented, data processing functionality is divided to two functions: rnp_protect() and rnp_process().

> What about doing the same with FFI?
> I.e. do not create duplicates of rnp_op_sign_set_hash(), rnp_op_sign_set_armor(), rnp_op_encrypt_set_armor(), and so on.

> Instead do rnp_op_protect_create(), rnp_op_execute(), rnp_op_destroy(), and misc rnp_op_set_something().
> Methods like rnp_op_clearsign_create(), rnp_op_sign_detached_create() may be added for user's convenience.

> And do the same with processing - rnp_op_process_create(), and use rnp_op_execute()/rnp_op_destroy() and so on.

> Within this we'll have less functions but more complicated logic inside of them.
> What do you think?

**Comment by dewyatt** [comment]
My own thoughts were that I don't like the idea of this:
> Within this we'll have less functions but more complicated logic inside of them.

I would somewhat prefer to have a greater quantity of simple functions rather than a lesser quantity of complex functions.

I also think we should appeal to our future user base and consider that they will likely be familiar with gpg operations like sign, verify, encrypt, decrypt, etc. Requiring API users to learn new concepts like protect and process immediately may be off-putting a little bit. (Also I don't really get the names process vs protect) I think this was maybe addressed above though via convenience functions.

Maybe a prototype interface with some actual arguments and things would help to understand the idea here.

**Comment by ronaldtse** [comment]
My take of this:
> Within this we'll have less functions but more complicated logic inside of them.

Is that we should avoid functions that are complex in general; instead complex ones should be split into smaller functions for easier understanding.

@dewyatt nothing helps set direction better than "desired sample code"; so I suggest we come up with a legitimate usage of the FFI.

One such use case is:
* signing and encrypting email, where the key is read from some database (esp. in Ruby) 😉

**Comment by ni4** [comment]
The idea behind process/protect is that we have two kinda of processing:
- forward: take raw data and apply some PGP protection (signing and/or encryption) to it, depending on options. It always has single input (raw data stream) and single output (binary signed-encrypted data, cleartext signed data, detached signature).
- backward: take some PGP data and process it (decrypt and/or verify), outputting the raw data (if any)  and signature(s) verification result (if any).

Agree that it would be hard for user to understand that why he needs to call `rnp_protect_data()` with some strange context instead of just call `rnp_sign_data()` when signing is needed.

So probably it would be just internal architecture - when all FFI calls go through a couple of functions, like it is now done on lib level/CLI : 
- `rnp_protect_file()`, which initializes input/output
- `rnp_call_protect_operation()`, which depending on signer/recipient list and options calls encrypt/encrypt-and-sign/sign method.
- `rnp_sign_src`, `rnp_encrypt_src`, `rnp_encrypt_sign_src` which build correct streams stack and call `process_stream_sequence`.
This approach also allows reuse of common code, like streams creation, data reading/writing and so on.

Processing of OpenPGP-protected data is easier since streams automatically detect contents and build the corresponding processing sequence.

**Comment by ronaldtse** [comment]
@ni4 that makes sense, but it would be really (really) helpful if you could help produce some sample code on how this is used in some application 😉

**Comment by ni4** [comment]
Get back to this after a while and it seems this would be an overhead and not much usable - for API user it is much handier to call specific function, like encrypt(), with desired minimum parameters and minimal configuration steps.
So closing this.
