### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#65]
From @dewyatt 

* Get rnp builds working on Travis
  * libbotan git will be required - I can likely copy what I did for ruby-botan.
* Get rnp tests running on Travis
* Switch Travis build to clang and utilize sanitizers
* Look into static analysis and code coverage solutions (we could discuss this after the basics above are done)

From @flowher 

* standard test run clang build and enable sanitizers - leak, address, undefined, memory (alternativelly we could use valgrind, but I prefer clang).
* If possible, it would be good to enable cppcheck (or setup coverity) and enable lcov/gcov for code coverage.
* As a another test improvement (for security) is to add fuzzing (https://github.com/google/oss-fuzz). It would be cool to have it but may take some time

**Comment by dewyatt** [comment]
@ronaldtse Please flip the switch for Travis CI when you get a chance.

**Comment by ronaldtse** [comment]
@dewyatt flipped!

**Comment by dewyatt** [comment]
Thanks @ronaldtse!

I took an initial stab at this and we've had our first build, which failed due to some memory leaks:

https://travis-ci.org/riboseinc/rnp/builds/227988366

Hopefully everyone received a notification on the build failure.

You can see that I used clang's [leak](https://clang.llvm.org/docs/LeakSanitizer.html), [address](https://clang.llvm.org/docs/AddressSanitizer.html), and [undefined](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) sanitizers. The [memory](https://clang.llvm.org/docs/MemorySanitizer.html) sanitizer (for detecting uninitialized reads) is not compatible with the address sanitizer. We could do separate runs with each, of course.

See the commit and commit message for more info on the Travis CI implementation as of now:
https://github.com/riboseinc/rnp/commit/9b79e8f47f4bc32f54694b78ea86bb7fd4fd3ea1

Feedback is very much welcome.

I think the remaining items are static analysis, coverage, and fuzzing. I'm looking in to these (include options listed above), and input is certainly appreciated.

**Comment by ronaldtse** [comment]
Really nice work @dewyatt ! It seems that some leaks come directly from the tests, but the rest are definitely real.

**Comment by flowher** [comment]
For static analysis you can consider https://clang-analyzer.llvm.org/, cppcheck or (my prefered option) coverity.

**Comment by dewyatt** [comment]
@flowher I agree we should try coverity, since no one else has a preference. I'll look into it ASAP.

I made a few more changes for CI.
We now have a test matrix for rnp:
https://travis-ci.org/riboseinc/rnp
```
normal   = build with clang, run cmocka rnp_tests
coverage = build with gcc, run cmocka rnp_tests, upload coverage
sanitize = build with clang (sanitizers), run cmocka rnp_tests
```
The sanitize build is currently allowed to fail, until we look into whether all the leaks are valid, if we can fix that, etc.

Code coverage for the cmocka tests is available here:
https://codecov.io/github/riboseinc/rnp/

**Comment by dewyatt** [comment]
@ronaldtse When you have a moment, can you [sign up for Coverity Scan](http://scan.coverity.com/users/sign_up), and then [register rnp](https://scan.coverity.com/projects/new?github_repo_name=riboseinc%2Frnp)?
I think that will get us moving in the right direction on that.

**Comment by ronaldtse** [comment]
@dewyatt I've done that. Is there anything else to configure?

**Comment by dewyatt** [comment]
@ronaldtse Thanks! The full steps are [here](https://docs.travis-ci.com/user/coverity-scan/) if you would like to complete them (which might be easiest, I'm not sure how permissions work).

**Comment by ronaldtse** [comment]
@dewyatt added the necessary configuration but doesn't seem working yet... would you mind having a look? Thanks!

**Comment by dewyatt** [comment]
@ronaldtse I think we're OK now. The rnp project isn't showing up on scan.coverity.com, but I think that can take 48 hours or so. Once it shows up, I think the rest of us can register and request access.

We'll have to maintain a separate travis.yml for the coverity_scan branch, otherwise it will build and attempt to upload multiple times. It looks like other projects do the same (botan). So we'll just do something like `git checkout coverity_scan && git rebase master && git push` when we want an analysis done.

**Comment by ronaldtse** [comment]
@dewyatt I've accepted you as a contributor for the project at Coverity, the project is showing now but we probably need to do more setup stuff like Component Configuration...

**Comment by dewyatt** [comment]
@ronaldtse Thanks! I don't really see any config options on my end...you may be seeing them since you're the project admin. Other than that, everything looks good to me. I see the issue list, and they appear valid at a glance.

I can take a closer look at component configuration if you would like, but I'm guessing we would have to bump my access level up from contributor to maintainer or something like that.

**Comment by ronaldtse** [comment]
@dewyatt I've bumped you to the maintainer role now and also added the badge to the README. Perhaps we don't need to further configure Coverity given that we have enough issues to work on.
