### ISSUE TITLE
Add option for json output for the packet dumper

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#668]
## Description

It would be handy to have packet dumper which outputs json object, and corresponding tests.

**Comment by dewyatt** [comment]
Just adding a note but the main reason I wanted this was so that it would be easier to test our generated packets, like checking the s2k iteration count in https://github.com/riboseinc/rnp/pull/728#issuecomment-418144160 and similar things. It's one thing to test some function input, but we really need to be testing generated packets.

**Comment by ni4** [comment]
Agree, @dewyatt .

**Comment by ni4** [comment]
Was fixed in PR #837 so closing this.
