### ISSUE TITLE
Failing build due to requirement of `/home/max`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#76]
@MohitKumarAgniotri it looks like the requirement of `/home/max` is failing the builds. Maybe we should use a temp directory for testing this instead?

**Comment by MohitKumarAgniotri** [comment]
My bad, will fix them ASAP.  Forgot to clean up after the initial testing
at my end.

On May 8, 2017 07:50, "ronaldtse" <notifications@github.com> wrote:

@MohitKumarAgniotri <https://github.com/MohitKumarAgniotri> it looks like
the requirement of /home/max is failing the builds. Maybe we should use a
temp directory for testing this instead?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/riboseinc/rnp/issues/76>, or mute the thread

**Comment by MohitKumarAgniotri** [comment]
@ronaldtse: I have fixed the issue. Shall I create a new pull request?

**Comment by ronaldtse** [comment]
@MohitKumarAgniotri yes please. Thanks!

**Comment by ronaldtse** [comment]
Fixed in #77
