### ISSUE TITLE
Add macOS build for travis

### ISSUE THREAD

**Issue by kwkwan** [riboseinc/rnp#786]
Previously we had a Jenkins job to run macOS builds but we need to migrate to Travis. The Jenkins is being decommissioned.

Here's the original script:
```sh
#!/bin/bash -x

whoami

export TRAVIS_PULL_REQUEST="true"
. ci/env-macos.sh

ci/before_install.sh
mkdir -p ${LOCAL_BUILDS}

ci/install.sh
ci/main.sh

```

**Comment by dewyatt** [comment]
I can take a look but with the GitLab CI work I've been doing it might make sense to wait a bit since 1) some of the scripts may change (currently they change quite a bit) and 2) we may want to request access to the macOS shared runners for GitLab instead of maintaining a separate CI env on Travis just for macOS.

**Comment by ronaldtse** [comment]
@dewyatt @ni4 Travis' macOS environment is relatively stable, can we move forward with this? Thanks!

**Comment by dewyatt** [comment]
I'm making some progress on this, having some linker errors building botan, so I'll be looking into that more today.

**Comment by dewyatt** [comment]
https://github.com/riboseinc/rnp/pull/802
