### ISSUE TITLE
Add FreeBSD build for Cirrus

### ISSUE THREAD

**Issue by kwkwan** [riboseinc/rnp#787]
Previously we had a Jenkins job to run FreeBSD builds but we need to migrate to Cirrus. The Jenkins is being decommissioned.

https://cirrus-ci.org/guide/FreeBSD/

Here's the original script:
```sh
#!/bin/bash -x

whoami

export TRAVIS_PULL_REQUEST="true"
. ci/env-freebsd.sh

ci/before_install.sh
mkdir -p ${LOCAL_BUILDS}

ci/install.sh
ci/main.sh
```

**Comment by dewyatt** [comment]
Why do they announce this after I put all this work into GitLab CI? :P (well I still prefer GitLab CI, since it's more open)

So, @ronaldtse just to be clear, I assume you want to minimize the infrastructure maintained by Ribose, and avoid maintaining VMs etc? I ask because I do believe it's pretty easy to run a GitLab Runner on your own FreeBSD system (local or cloud or whatever) and tie it to gitlab.com. But if the goal is to avoid that, Cirrus seems like an interesting option for FreeBSD.

It's starting to sound like we'll end up using GitLab CI for Linux, Cirrus CI for FreeBSD, and Travis CI for macOS. Not that it's a bad thing, but it might be nice to squeeze into a single (preferably open-source, but that's just IMO) platform to avoid maintaining all these separate environments.

(Also, I'll take a look at the build being broken on FreeBSD in a minute here.)

**Comment by ronaldtse** [comment]
I thought GitLab didn't support FreeBSD? As you mentioned, we do want to minimize infrastructure maintained ourselves for open projects. We are obviously open to options, so it's all fluid. I agree the goal is to squeeze into a single platform at an abstract level, but it's not always the most practical. 😉

**Comment by dewyatt** [comment]
> I thought GitLab didn't support FreeBSD?

They don't provide any free shared runners like they do for Linux, but I believe you can still run your own FreeBSD runner and register it to your project on gitlab.com. Same for macOS (IIRC they actually do have free shared macOS runners, but you have to be a big popular project to qualify or something).

**Comment by ronaldtse** [comment]
Indeed, it would be much easier to have the CI build occur on external services rather than having to maintain our own computing for so many reasons. *BSD, Linux and macOS are different enough already, so even using three services aren't that big a stretch. 

On our Metanorma builds, we're already doing Travis for Linux and macOS, and AppVeyor for Windows. So it's not a first for us anyway. The benefit for doing so is to allow whoever has the platform expertise to implement its own flow, rather than requiring one person (who's in charge of the CI) to be an expert in configuring for all platforms.

**Comment by dewyatt** [comment]
Sounds reasonable to me. I do see a few things broken with our build on FreeBSD, I have it building successfully locally now so hopefully will get a PR done for that today (possibly need more time for proper fixes).

**Comment by ronaldtse** [comment]
Now that #789 is fixed this can proceed.

**Comment by ronaldtse** [comment]
This repo is now subscribed to Cirrus CI, so @dewyatt please feel free to start with this 👍

**Comment by ronaldtse** [comment]
Any updates on this @dewyatt? Thanks!

**Comment by dewyatt** [comment]
Added in https://github.com/riboseinc/rnp/pull/799
