### ISSUE TITLE
FFI key to json: key flags and key usage.

### ISSUE THREAD

**Issue by ni4** [riboseinc/rnp#841]
## Description

Currently, when key is exported to JSON, key flags are separated to 'flags' and 'usage'.
While both are stored in the single 'key flags' signature subpacket.
Should not we glue them together to the single 'flags' field?
If not then to which of them add the new flags from #783 ?

cc @dewyatt @ronaldtse

**Comment by dewyatt** [comment]
@ni4 Are you referring to `rnp_key_to_json` here?

**Comment by ni4** [comment]
@dewyatt Yes. Also we have some mess in `rnp_key_allows_usage` which, first calls `str_to_key_flag` and then it refers to the `key_usage_map`. While we have `key_flags_map` as well.

**Comment by dewyatt** [comment]
IIRC my initial thought when I implemented this stuff was that it made sense to treat usage and flags separately because you can pretty much categorize key flags as:

* usage (the two additional flags from the RFC bis make sense here)
* other, almost-never-used flags ("split", "shared")

Similarly I merged the "encrypt comms" and "encrypt storage" concepts into a usage of "encrypt" since it seems that nobody really uses this distinction.

What kind of changes did you have in mind?

**Comment by ni4** [comment]
@dewyatt Thanks for explanation. I thought that it would make sense to leave  just a single `flags` entity. However, now, after your explanation, it's logical to leave things as they are.
