### ISSUE TITLE
Portability of vasprintf and asprintf 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#9]
`vasprintf` and `asprintf` are provided in *BSD but in Linux requires defining `__GNU_SOURCE__` to work.

`asprintf` already has its equivalent of `pgp_asprintf` in `libnetpgp` but not `vasprintf`.

We should probably borrow a compatible implementation of `vasprintf` that matches the BSD license.

**Comment by shaunwheelhouse** [comment]
Having given it some consideration I think that it would be productive to make a list of targets that would be impacted by the absence of these functions from both BSD and GNU. While we could include a suitably permissive borrowed implementation they are yet another thing that needs to be maintained. I think we'd be better off requiring the build target to provide them unless ubiquity is a major requirement, however I'm _tentatively_ optimistic that we could borrow them from OpenBSD's libc without too many troubles if necessary.

Before that I'll do a run over of where they're used (in 11 places by my count), there may be places where they're convenient but could be done with a fixed sized buffer.

**Comment by shaunwheelhouse** [comment]
For reference here are some notes on where they're used. A few were comments and forward declarations.

1. lib/packet-print.c:pgp_sprint_keydata:465

   Formats five strings and an integer from a PGP key to a string. We could consider using a user-supplied buffer here and raising an error if it would have overflowed.

2. lib/packet-print.c:pgp_hkp_sprint_keydata:617

   Formats numeric fields to a fingerprint string? Could adopt the same strategy as above.

3. lib/packet-show.c:add_bitmap_entry:471

   There's probably no need to use a dynamic buffer here.

4. lib/ssh2pgp.c:pgp_ssh2pubkey:323

   This only joins strings. A sane fixed sized buffer would be a reasonable replacement I think.

5. netpgpverify/libverify.c:obuf_printf:227

   Need to inspect callers; caller provides format string.

6. netpgpverify/libverify.c:2474:read_ssh_file

   Performs the same format operation as in (4).

4 and 6 may be deprecated entirely because they concern SSH keys. I think this is a pretty good case for abolishing these calls entirely.

**Comment by ronaldtse** [comment]
@shaunwheelhouse completely agree: places that can be used with a fixed buffer should do exactly that.

5. is only used for printing for human reading in `libverify/libverify.c`. Instead of making one dynamic buffer, perhaps we can join up smaller string buffers with deterministic length when printing to screen.

For the calls about SSH keys, a number of people use PGP keys for SSH authentication, and seems to be increasingly so with devices like YubiKeys. We should keep support of converting PGP keys into SSH keys.

**Comment by shaunwheelhouse** [comment]
That's fair. In that case I'll get working on pruning the unnecessary points out now. 👍

**Comment by shaunwheelhouse** [comment]
Tonight I "resolved" 5/6 of the cases but I'm not yet happy with a couple of arbitrary sizes that I used. It would be useful to instate some limits on the sizes of some of the fields so that there's a consistent base to work from. I'll work on that in the morning.

The fifth case, `obuf_printf`, is used extensively throughout its module and will need to either be assigned a statically sized buffer or each dependent case will need to be replaced with equivalent code.

**Comment by ronaldtse** [comment]
@shaunwheelhouse it would be exciting to get rid of (or replace) the `obuf_printf` function entirely 👍

**Comment by shaunwheelhouse** [comment]
@ronaldtse I'll look into that then while I wrap this issue up. 👍

**Comment by ronaldtse** [comment]
Thank you @shaunwheelhouse !

**Comment by ronaldtse** [comment]
@shaunwheelhouse can we close this issue now?

**Comment by shaunwheelhouse** [comment]
@ronaldtse the instance within obuf_printf is yet to be replaced, but if you would prefer to make that its own issue and close this you're welcome to.

**Comment by ronaldtse** [comment]
@shaunwheelhouse Nah then we'll wait for that here then. It is more exciting to get rid of them all at once 👍

**Comment by shaunwheelhouse** [comment]
@ronaldtse Sounds good. I'll get on to that now but I suspect it will take a little bit of time, it's quite embedded in its module. I'm going to see if io vectors would be a suitable replacement vs. re-sizing a contiguous buffer.

**Comment by ni4** [comment]
I'm moving ahead and closing this since we do not have calls to these functions anywhere.

**Comment by ronaldtse** [comment]
Thanks!
